# Generated by Django 4.1.4 on 2022-12-31 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('shipping_address', models.TextField(blank=True, max_length=30, null=True)),
                ('loyalty_points', models.CharField(blank=True, max_length=30, null=True)),
                ('payment', models.CharField(max_length=120)),
                ('cc_num', models.CharField(max_length=120)),
                ('exp', models.CharField(max_length=120)),
                ('cvv', models.CharField(max_length=120)),
            ],
        ),
    ]
